(function ($) {
    var mainHolder
    var svgObject, svgOutline, svgColor
    var fillSpeed = .75
    var closeOffset

    var appliedColor = "rgb(255, 0, 0)"; // Default is white
    //Add click listener to all the options in the color bar
    var colorOptions = document.getElementsByClassName("color-option");
    for(i = 0; i < colorOptions.length; i++) {
        colorOptions[i].addEventListener("click", function() { 
            // Set the paintbrush color
            appliedColor = this.style.backgroundColor;
            // console.log("Grabbing the color: " + appliedColor);
            // Show icon on the swatch indicating this color is selected
            // 1. Clear the previous icon
            for(i = 0; i < colorOptions.length; i++) {
                colorOptions[i].innerHTML = ""; // Capa_1 is the ID name given by FontAwesome
            }
            // 2. Add the icon to the color just selected   
            var elementID =  this.id;
            // TODO: It would be nice if SVG color could be changed via JavaScript instead of having two different SVG files
            // For some reason, targeting by ID then changing fill is not working
            // Re-investigate this as a nice-to-have
            //var colorSelectedIcon = document.getElementById("Capa_1"); // Capa_1 is the ID name given by FontAwesome
            if(elementID == "black") {
                // Use a white icon over black
                this.innerHTML = "<img src='images/buttons/check-mark_white.svg' alt='The color black has been selected'>";
            } else {
                // Otherwise make the icon black
                this.innerHTML = "<img src='images/buttons/check-mark_black.svg' alt='The color " + elementID + " has been selected'>";
            }
        });
        colorOptions[i].addEventListener("mouseover", function() { 
            // Need a mouseover trigger because hover state is not supported by CSS grid
            // The color swatches are CSS grid cells
            this.style.cursor = "pointer";
        });
    }

    var leftInvisibleButton = document.getElementById("left-invisible-button");
    leftInvisibleButton.addEventListener("click", function() { 
        colorsPainted[0] = appliedColor;
        colorBorder("left");
    });

    var middleInvisibleButton = document.getElementById("middle-invisible-button");
    middleInvisibleButton.addEventListener("click", function() { 
        colorsPainted[1] = appliedColor;
        colorBorder("middle");
    });

    var rightInvisibleButton = document.getElementById("right-invisible-button");
    rightInvisibleButton.addEventListener("click", function() { 
        colorsPainted[2] = appliedColor;
        colorBorder("right");
    });

    function colorMe() {
        // Color a border directly
        // console.log("--- Coloring with " + appliedColor);
        var section = this.id;
        if (section == "left") {
            colorsPainted[0] = appliedColor;
        }
        else if (section == "middle") {
            colorsPainted[1] = appliedColor;
        }
        else if (section == "right") {
            colorsPainted[2] = appliedColor;
        }
        TweenMax.to(this, fillSpeed, { stroke: appliedColor });
        if(appliedColor != "rgb(255, 255, 255)") {
            console.log("Show the reset button");
            toggleButtonInteractability("reset-button", "on");
        } else {
            //console.log("Are all quadrants white?");
            var counter = 0;
            for(i = 0; i < colorsPainted.length; i++) {
                console.log(colorsPainted[i]);
                if(colorsPainted[i] == "rgb(255, 255, 255)") {
                    counter++;
                }
            }
            if(counter == 4) {
                //console.log("Hide the reset button");
                toggleButtonInteractability("reset-button", "off");
            }
        }
    }

    function colorBorder(svgId) {
        // Color an border that surrounds invisible click area in the center of the quadrant
        // id generated by callback function attached to invisible button UI
        console.log("Coloring border!");
        var svg = document.getElementById(svgId);
        TweenMax.to(svg, fillSpeed, { stroke: appliedColor });
        console.log("Applied color: " + appliedColor);
        if(appliedColor != "rgb(255, 255, 255)") {
            //console.log("Showing the reset button");
            toggleButtonInteractability("reset-button", "on");
        } else {
            //console.log("Are all quadrants white?");
            var counter = 0;
            for(i = 0; i < colorsPainted.length; i++) {
                console.log(colorsPainted[i]);
                if(colorsPainted[i] == "rgb(255, 255, 255)") {
                    counter++;
                }
            }
            if(counter == 4) {
                //console.log("Hide the reset button");
                toggleButtonInteractability("reset-button", "off");
            }
        }
    }

    $.fn.makeSVGcolor = function (svgURL) {
        mainHolder = this

        $(this).load(svgURL, function () {
            svgObject = $('svg', this)
            //console.log(svgObject)
            svgColor = $('g:nth-child(2)', svgObject).children()
            //console.log(svgColor)
            svgOutline = $('g:nth-child(1)', svgObject).children()
            $(svgColor).on('click', colorMe)
        });
    }

    $('#colorable-svg').makeSVGcolor('images/trays/color-outlines_three-columns.svg')

}(jQuery));
